---
- Id: 846F823E-C0D3-4AF0-AD51-0F9573379057
  Name: Standard thumbnail-and-transcode
  Steps:
    - Id: 702DBDC5-CE51-4760-82E4-01BC1FB4771E
      PredeterminedType: analysis
      KubernetesTemplateFile: config/AnalysisJobTemplate.yaml
    - Id: 5F64F20F-B748-4930-B22E-4178F730BD4F
      PredeterminedType: thumbnail
      KubernetesTemplateFile: config/AnalysisJobTemplate.yaml
    - Id: 6FF216B6-A395-4237-A9F2-2FEB3F24823E
      PredeterminedType: transcode
      KubernetesTemplateFile: config/AnalysisJobTemplate.yaml