apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: MediaFlipper
    stack: MediaFlipper
  name: shared-data-mediaflipper
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: basic