apiVersion: v1
kind: ConfigMap
metadata:
  name: mediaflipper-webapp-config
data:
  serverconfig.yaml: |
    scratch:
      localpath: /mnt/shared-data
    redis:
      address: redis-mediaflipper:6379
      password: changeme
      dbNum: 0
  AnalysisJobTemplate.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: analysis-job-template
    spec:
      template:
        spec:
          containers:
            - name: analyser
              image: guardianmultimedia/mediaflipper:DEV
              imagePullPolicy: Always
              env:
                - name: WRAPPER_MODE
                  value: analyse
                - name: JOB_ID
                  value: overwritten
                - name: FILE_NAME
                  value: overwritten
                - name: WEBAPP_BASE
                  value: overwritten
                - name: MAX_RETRIES
                  value: "10"
              command: ["/opt/mediaflipper/wrapper"]
              volumeMounts:
                - mountPath: /mnt/shared-data
                  name: shared-data
          restartPolicy: OnFailure
          volumes:
            - name: shared-data
              persistentVolumeClaim:
                claimName: shared-data-mediaflipper
      backoffLimit: 4
  standardjobtemplate.yaml: |
    ---
    - Id: 846F823E-C0D3-4AF0-AD51-0F9573379057
      Name: Standard thumbnail-and-transcode
      Steps:
        - Id: 702DBDC5-CE51-4760-82E4-01BC1FB4771E
          PredeterminedType: analysis
          KubernetesTemplateFile: config/AnalysisJobTemplate.yaml
        - Id: 702DBDC5-CE51-4760-82E4-01BC1FB4771E
          PredeterminedType: thumbnail
          KubernetesTemplateFile: config/AnalysisJobTemplate.yaml