apiVersion: v1
kind: ConfigMap
metadata:
  name: mediaflipper-webapp-settings
data:
  mp4proxy.yaml: |
    ---
    - settingsid: "7FEC2963-6A1D-46A2-8DE1-62DF939F6755"
      name: mp4proxy
      description: Small MP4 file suitable for use as a video proxy
      wrapper:
        format: mp4
      audio:
        codec: aac
        bitrate: 128000
        channels: 2
        samplerate: 48000
      video:
        codec: h264
        crf: 26
        preset: fast
        scale:
          scalex: 1280
          scaley: -1
          allowupscaling: false
  wmv.yaml: |
    ---
    - settingsid: "7B37FEBC-18C1-4626-8941-10A8AFE1B51C"
      name: wmvconvert
      description: WMV file suitable for presentations
      wrapper:
        format: asf
      audio:
        codec: wmav2
        bitrate: 128000
        channels: 2
        samplerate: 48000
      video:
        codec: wmv2
        bitrate: 4194304  #4mbit/s
        scale:
          scalex: 1280
          scaley: -1
          allowupscaling: false
