apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webapp-role-mediaflipper
rules:
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods","services"]
    verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: webapp-rolebind-mediaflipper
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: webapp-role-mediaflipper
  apiGroup: rbac.authorization.k8s.io