apiVersion: v1
kind: ConfigMap
metadata:
  name: mediaflipper-webapp-config
data:
  serverconfig.yaml: |
    scratch:
      localpath: /mnt/shared-data
    redis:
      address: redis-mediaflipper:6379
      password: changeme
      dbNum: 0
    settingspath: /opt/mediaflipper/settings
  AnalysisJobTemplate.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: analysis-job-template
    spec:
      template:
        spec:
          containers:
            - name: mediaflipper
              image: guardianmultimedia/mediaflipper:16
              #imagePullPolicy: Always
              env:
                - name: WRAPPER_MODE
                  value: analyse
                - name: JOB_ID
                  value: overwritten
                - name: FILE_NAME
                  value: overwritten
                - name: WEBAPP_BASE
                  value: overwritten
                - name: MAX_RETRIES
                  value: "10"
              command: ["/opt/mediaflipper/wrapper"]
              volumeMounts:
                - mountPath: /mnt/shared-data
                  name: shared-data
          restartPolicy: OnFailure
          volumes:
            - name: shared-data
              persistentVolumeClaim:
                claimName: shared-data-mediaflipper
      backoffLimit: 4
  standardjobtemplate.yaml: |
    ---
    - Id: 846F823E-C0D3-4AF0-AD51-0F9573379057
      Name: Standard thumbnail-and-transcode
      Steps:
        - Id: 702DBDC5-CE51-4760-82E4-01BC1FB4771E
          PredeterminedType: analysis
          InProgressLabel: Analysing...
          KubernetesTemplateFile: config/AnalysisJobTemplate.yaml
        - Id: 5F64F20F-B748-4930-B22E-4178F730BD4F
          PredeterminedType: thumbnail
          InProgressLabel: Extracting thumb...
          KubernetesTemplateFile: config/AnalysisJobTemplate.yaml
          ThumbnailFrameSeconds: 2
        - Id: 6FF216B6-A395-4237-A9F2-2FEB3F24823E
          PredeterminedType: transcode
          InProgressLabel: Transcoding...
          KubernetesTemplateFile: config/AnalysisJobTemplate.yaml
          TranscodeSettingsId: 7FEC2963-6A1D-46A2-8DE1-62DF939F6755
    - Id: BAF0DCB9-7DE1-4D33-9DFF-B7AB565C47E8
      Name: Convert to WMV
      Steps:
        - Id: 702DBDC5-CE51-4760-82E4-01BC1FB4771E
          PredeterminedType: analysis
          InProgressLabel: Analysing...
          KubernetesTemplateFile: config/AnalysisJobTemplate.yaml
        - Id: 6FF216B6-A395-4237-A9F2-2FEB3F24823E
          PredeterminedType: transcode
          InProgressLabel: Transcoding...
          KubernetesTemplateFile: config/AnalysisJobTemplate.yaml
          TranscodeSettingsId: 7B37FEBC-18C1-4626-8941-10A8AFE1B51C